services:
  # PostgreSQL
  postgres_db:
    image: postgres:18
    container_name: turbine_postgres_db
    networks:
      - windturbineNet
    environment:
      POSTGRES_DB: windTurbineMaintenance
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d windTurbineMaintenance"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Kafka with Kraft
  kafka:
    image: apache/kafka:4.1.1
    container_name: turbine_kafka
    networks:
      - windturbineNet
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_KRAFT_CLUSTER_ID: '5L6g3nShT-eMCtK--X86sw'
      KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
      image: obsidiandynamics/kafdrop:latest
      container_name: turbine_kafdrop
      networks:
        - windturbineNet
      ports:
        - "9000:9000"
      environment:
        KAFKA_BROKERCONNECT: kafka:29092
      depends_on:
        - kafka

networks:
  windturbineNet:
    driver: bridge